bdd-pact:
  ng-frontend:
    base-url: http://localhost:4200
  products-catalogue-service:
    base-url: http://localhost:8081
  offers-service:
    base-url: http://localhost:8082
zuul:
  prefix: /api/v1
  strip-prefix: true
  routes:
    offers:
      path: /offers/**
      url: ${bdd-pact.offers-service.base-url}
    products:
      path: /products/**
      url: ${bdd-pact.products-catalogue-service.base-url}
      strip-prefix: false
    categories:
      path: /categories/**
      url: ${bdd-pact.products-catalogue-service.base-url}
      strip-prefix: false
