bdd-pact:
  ng-frontend:
    base-url: http://localhost:4200
  products-service:
    base-url: http://localhost:8081
  offers-service:
    base-url: http://localhost:8082
zuul:
  routes:
    products-catalogue-service:
      path: /api/v1/products/**
      url: ${bdd-pact.products-service.base-url}
    offers-service:
      path: /api/v1/offers/**
      url: ${bdd-pact.offers-service.base-url}
    ng-frontend:
      path: /**
      url: ${bdd-pact.ng-frontend.base-url}
