server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  datasource:
    schema: classpath:sql/schema.sql
---
spring:
  profiles: demo
  datasource:
    data: classpath:sql/data.sql
