version: '3'
services:
  ng-frontend:
    image: 'jagilpe/ng-frontend'
    expose:
      - "80"
    networks:
      - frontend
    ports:
      - 4200:80
  api-gateway:
    image: 'jagilpe/api-gateway:latest'
    environment:
      - PRODUCTS_CATALOGUE_SERVICE_URL=http://product-catalog-service:8080
      - OFFERS_SERVICE_URL=http://offers-service:8080
      - NG_FRONTEND_URL=http://localhost:4200
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
  product-catalog-service:
    image: 'jagilpe/product-catalog-service:latest'
    environment:
      - ACTIVE_PROFILES=demo
    networks:
      - backend
  offers-service:
    image: 'jagilpe/offers-service:latest'
    environment:
      - ACTIVE_PROFILES=demo
    networks:
      - backend
networks:
  frontend: ~
  backend: ~
