version: '3'
services:
  postgres:
    image: postgres
    healthcheck:
      test: psql -U postgres postgres --command "select 1"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  broker_app:
    image: dius/pact-broker
    ports:
      - "1080:80"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: postgres
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
